/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{js,jsx,ts,tsx}", "./public/index.html"],
  theme: {
    extend: {
      colors: {
        black: "#000000",
        primary: "#8CFF2E",
        buttonBg: "#050505",
        textWhite: "#FFFFFF",
        textGray: "#A3A3A3",
        cardBg: "#0D0D0D",
        bgColor: "#FAFAFA",
        cardBorder: "#1F1F1F",
        buttonText: "#2F2F2F",
        shadow: "#8CFF2F03",
        white: "#FFFFFF",
        blogCardBg: "#0D0D0D",
        inputBg: "#2F2F2F",
        formBg: "#0D0D0D",
        wishlistCardBg: "#0D0D0D",
        wishlistInputBg: "#2F2F2F",
        wishlistButtonBg: "#8CFF2E",
        clarioGreen: "#8CFF2E",
        clarioBlack: "#000000",
        clarioWhite: "#FFFFFF",
        clarioIconBg: "#FFFFFF",
        clarioIconActiveBg: "#000000",
        headerBorder: "#2F2F2F",
        textSecondary: "#939494",
        transactionTitle: "#060F0D",
        transactionSub: "#727272",
        exportBorder: "#EBEBEB",
        exportBg: "#F8F8F8",
        addBtnBorder: "#629298",
        addBtnBg: "#050505",
        addBtnText: "#F8F8F8",
        transactionTextBrand: "#060F0D",
        transactionTextMuted: "#A5A5A5",
        transactionPositive: "#588D73",
        transactionNegative: "#C32F27",
        transactionBorder: "#EBEBEB",
        transactionBg: "#F8F8F8",
        transactionTagPositiveBg: "#EAF3EF",
        transactionTagNegativeBg: "#FCEAE9",
        transactionTableHeaderBg: "#F0F0F0",
        transactionDateText: "#727272",
        expenseBubbleGroceries: "#1A2E05",
        expenseBubbleTransport: "#44920E",
        expenseBubbleOthers: "#99FF33",
        // Category Page Colors
        categoryPageBg: "#FAFAFA",
        categoryCardBorder: "#D8D8D8",
        categoryCardBg: "#FFFFFF",
        categorySidebarBg: "#FDFDFD",
        categorySidebarBorder: "#F5F5F4",
        categoryTextMain: "#000000",
        categoryTextSecondary: "#757575",
        categoryTextMuted: "#CECECE",
        categoryTextPrice: "#8C8C8C",
        categoryTextLabel: "#CCCCCC",
        categoryTitleSidebar: "#6B6A6A",
        categoryLegendText: "#A4A4A3",
        categoryLegendSub: "#BCBCBC",
        categoryLegendMain: "#A4A4A3",
        // Profile Page Colors
        profileTitle: "#3B3B3A",
        profileSectionTitle: "#646463",
        profileBillingTitle: "#656565",
        profileBorder: "#F0F0F0",
        profileBillingBorder: "#E5E5E5",
        profileInputText: "#8F8F8F",
        profileInputBillingText: "#939292",
        profileInputBillingBorder: "#C4C4C4",
        profileDeleteBtnText: "#484848",
        profileSubTierBg: "#FCFDFD",
        profileSubTierBorder: "#F4F4F4",
        profileSubTierText: "#717271",
        // Budget specific
        budgeBg: "#F8F8F8",
        budgeBorder: "#EBEBEB",
        budgeText: "#060F0D",
        budgeBadgeBg: "#F4F4F4",
        // Graph specific
        graphBudget: "#2E6600",
        graphSpend: "#5CCC00",
        graphBudgetUnselected: "#2E660033",
        graphSpendUnselected: "#5CCC0033",
        graphBorder: "#C2D0D2",
        graphSpendUnselectedBorder: "#C2D0D6",
        // Breakdown specific
        breakdownHeader: "#F0F0F0",
        breakdownTextLight: "#A5A5A5",
        progressBarStart: "#588D73",
        progressBarEnd: "#3B6064",
        progressBarTrack: "#809B9E",
        breakdownTextUsed: "#3B6064",
        // Goal specific
        goalTitle: "#525252",
        goalText: "#0D0D0D",
        goalCardBg: "#FEFEFE",
        goalCardBorder: "#FBFBFB",
        goalSubtitle: "#B6B6B5",
        goalOnTrackBg: "#76C735",
        goalOnTrackBorder: "#6AC325",
        goalOnTrackText: "#C6E9AC",
        goalPendingBg: "#D3443D",
        goalPendingBorder: "#D43531",
        goalPendingText: "#E8B0AE",
        goalDelayedBg: "#D6D6D8",
        goalDelayedBorder: "#E1E1E1",
        goalDelayedText: "#F4F4F5",
        goalDate: "#9B9B9A",
        // Goal History specific
        goalHistoryHeaderBg: "#F1F1F1",
        goalHistoryHeaderText: "#767676",
        goalHistoryRowText: "#ADADAD",
        archivedBtnBg: "#CE413F",
        archivedBtnBorder: "#CF302D",
        archivedBtnText: "#E6ADAA",
        // Create Goal Page Colors
        createGoalBg: "#FEFEFE",
        createGoalTitle: "#4C4C4B",
        createGoalLabel: "#757474",
        createGoalBorder: "#8D8D8D",
        createGoalHeading: "#000000",
        createGoalTableHeader: "#737272",
        createGoalTableRowBg: "#F0F0F0",
        createGoalTableRowText: "#ABAAAA",
        createGoalFundingTitle: "#000000",
        createGoalCardBorder: "#C4C4C4",
        createGoalButtonCancelBg: "#F0F0F0",
        createGoalButtonCancelText: "#484948",
        // Financial Report specific
        reportBg: "#FAFAFA",
        reportTitle: "#000000",
        reportSubtitle: "#969696",
        reportButtonDateBg: "#FCFCFC",
        reportButtonDateBorder: "#F0F1F1",
        reportButtonDateText: "#BFBFBF",
        reportFilterBorder: "#E1DEDC",
        reportFilterBg: "#FEFEFE",
        reportFilterText: "#A0A1A1",
        reportDownloadBorder: "#3C3D3D",
        reportDownloadBg: "#1B1A1B",
        reportDownloadText: "#FFFFFF",
        reportShareBg: "#F0F1F1",
        reportShareText: "#A4A5A5",
        reportCominloadBg: "#F1F1F1",
        reportCominloadBorder: "#F0F1F1",
        reportCominloadText: "#B2B4B6",
        reportCardBg: "#FDFDFD",
        reportCardTitle: "#878685",
        reportCardSubtitle: "#ABABAB",
        reportIncomeText: "#565555",
        reportExpenseText: "#4E4D4C",
        reportTrendTitle: "#8A8989",
        reportTrendYAxis: "#B5B4B5",
        reportTrendXAxis: "#BFBFBF",
        reportChartIncome: "#8CFF2E",
        reportChartExpense: "#565555",
        reportChartTrendIncome: "#8CFF2E",
        reportChartTrendExpense: "#8C8C8C",
        // Recent Transaction specific
        recentTransactionTitle: "#8E8D8D",
        recentTransactionHeaderBg: "#F1F1F1",
        recentTransactionHeaderText: "#767676",
        recentTransactionRowText: "#A7A7A6",
        statusReceivedBg: "#73C932",
        statusReceivedBorder: "#63C61F",
        statusReceivedText: "#C0E6A1",
        statusCompletedBg: "#73C932",
        statusCompletedBorder: "#5FBF19",
        statusCompletedText: "#C1E6A0",
        // Reminder Page Colors
        reminderTitle: "#4F4E4D",
        reminderCardGreen: "#8CFF2E",
        reminderCardDark: "#333C2F",
        reminderCardBlack: "#050505",
        reminderCardGray: "#D6DFD0", // Normalized from D6DFD0FE
        reminderCardWhite: "#FCFDFD",
        reminderPreferencesBg: "#FDFDFD", // Normalized from FDFDFDFE
        reminderPreferencesBorder: "#F6F6F6",
        reminderCompletionBg: "#FCFCFC",
        reminderCompletionBorder: "#F4F5F4",
        reminderTextMain: "#000000",
        reminderTextGray: "#B5B9B2",
        reminderTextMuted: "#9DA296",
        reminderSubtext: "#777D70",
        reminderTextRow2: "#63665F",
        reminderAmountRow2: "#777B72",
        reminderSubRow2: "#A9AFA4",
        reminderTextRow3: "#737371",
        reminderPrefTitle: "#6D6D6C",
        reminderPrefLabel: "#A3A3A2",
        reminderPrefTime: "#A5A5A4",
        reminderCompletionText: "#717171",
        reminderBorderRow2: "#DEE4D9",
        reminderBorderRow3: "#EEEEEE",
        // Setting Page Colors
        settingPageBg: "#FAFAFA",
        settingTitle: "#3D3D3C",
        settingSearchBorder: "#868585",
        settingSearchText: "#000000",
        settingCardBg: "#FFFFFF",
        settingCardBorder: "#F0F0F0",
        settingCardBg2: "#FDFDFD",
        settingCardBorder2: "#F3F3F4",
        settingCardBorder3: "#F6F7F6", // Also for third card
        settingTextDark: "#000000",
        settingTextGray: "#A2A2A1",
        settingTextLightGray: "#A1A1A0",
        settingTextMuted: "#A09F9F",
        settingInputBg: "#FBFBFB",
        settingInputText: "#B1B2B2", // Also used for some placeholders? check req
        settingSectionTitle: "#60605F",
        settingInputBgWhite: "#FFFFFF",
        settingPlaceholder: "#9A9A99",
        settingTextMedium: "#666665",
        settingTextRegular: "#A7A7A7",
        settingIntegrationTitle: "#616161",
        settingBankText: "#9C9C9C",
        settingSubscriptionTitle: "#727372",
        settingProPlan: "#A2B294",
        settingButtonSaveBg: "#050505",
        settingButtonSaveText: "#FFFFFF",
        settingButtonCancelBg: "#F0F0F0",
        settingButtonCancelText: "#313030",
        settingSubscriptionBg: "#FCFCFC",
      },
      screens: {
        xlg: "1440px",
      },
      fontFamily: {
        manrope: ["Manrope", "sans-serif"],
        inter: ["Inter", "sans-serif"],
        satoshi: ["Satoshi", "sans-serif"],
        poppins: ["Poppins", "sans-serif"],
      },
      fontSize: {
        "budge-label": "12.94px",
        "budge-value": "15.94px",
      },
      extend: {
        colors: {
          // ... existing colors ...
          monthlyCardBorder: "#E8E8E8",
          monthlyTextMain: "#1F1F1F",
          monthlyTextSub: "#8A8A8A",
          monthlyButtonDownloadBorder: "#7B9069",
          monthlyButtonDownloadText: "#7B9069",
          monthlyButtonShareBg: "#7B9069",
          monthlyButtonShareBorder: "#353A30",
          monthlyButtonDateBg: "#7B9069",
          monthlyButtonDateBorder: "#353A30",
          monthlyIncomeBg: "#5CCC00",
          monthlyExpenseBg: "#2E6600",
          monthlySavingBg: "#050505",

          // Financial Summary Colors
          summaryCardBorder: "#C4CDBB",
          summaryTitle: "#050505",
          summarySubtitle: "#8A8A8A",
          summaryIncomeBg: "#FFFFFF",
          summarySpendingBg: "#5CCC00",
          summaryBudgetBg: "#2E6600",
          summarySavingBg: "#050505",
          summaryIncomeText: "#050505",
          summarySpendingText: "#050505",
          summaryBudgetText: "#FFFFFF",
          summarySavingText: "#FFFFFF",
          summaryLabelDark: "#16240A", // For Income/Spending labels
          summaryLabelLight: "#FFFFFF", // For Budget/Saving labels
          summaryDescDark: "#111111",
          summaryDescLight: "#FFFFFF",

          // Recent Transaction New UI Colors
          recentBorder: "#E8E8E8",
          recentTextTitle: "#050505",
          recentTextSub: "#8A8A8A",
          recentMutationBorder: "#050505",
          recentGreen: "#2E6600",
          recentDark: "#050505",
          recentSortBg: "#7B9069",
          recentSortBorder: "#353A30",
          recentTableTitle: "#1F1F1F",
          recentTableNegative: "#906969",
          recentPendingEnd: "#DFE4DB",
          recentPendingBg: "#FFFFFF",

          // Budget Goals specific
          budgetGoalTextMain: "#1F1F1F",
          budgetGoalTextSub: "#8A8A8A",
          budgetGoalBorder: "#E8E8E8",
          budgetGoalBtnBorder: "#7B9069",
          budgetGoalManageStart: "#0B1A00",
          budgetGoalManageEnd: "#050505",
          budgetGoalIconBg1Start: "#7B9069",
          budgetGoalIconBg1End: "#050505",
          budgetGoalIconBg2: "#DFE4DB",

          // Expense Distribution specific
          distTextMain: "#1F1F1F",
          distTextSub: "#8A8A8A",
          distPie28: "#F1FFE5",
          distPie30: "#050505",
          distPie16: "#5CCC00",
          distPie26: "#2E6600",

          // Monthly Financial Trend Specific Colors
          monthlyCardBorder: "#E8E8E8",
          monthlyTextMain: "#1F1F1F",
          monthlyTextSub: "#8A8A8A",
          monthlyButtonDownloadBorder: "#7B9069",
          monthlyButtonDownloadText: "#7B9069",
          monthlyButtonShareBg: "#7B9069",
          monthlyButtonShareBorder: "#353A30",
          monthlyButtonShareText: "#FFFFFF",
          monthlyButtonDateBg: "#7B9069",
          monthlyButtonDateBorder: "#353A30",
          monthlyButtonDateText: "#FFFFFF",
          monthlyIncomeBg: "#5CCC00",
          monthlyExpenseBg: "#2E6600",
          monthlySavingBg: "#050505",
          monthlyIncomeText: "#000000",
          monthlyExpenseText: "#000000",
          monthlySavingText: "#000000",
          monthlyLabel: "#1F1F1F",
          monthlyValueText: "#8A8A8A",
          monthlyGridBorder: "#E8E8E8",

          // Financial Summary Specific Colors
          summaryCardBorder: "#C4CDBB",
          summaryTitle: "#050505",
          summarySubtitle: "#8A8A8A",
          summaryTotalIncomeBg: "#FFFFFF",
          summaryTotalSpendingBg: "#5CCC00",
          summarySpentBudgetBg: "#2E6600",
          summaryTotalSavingBg: "#050505",

          summaryTotalIncomeText: "#16240A",
          summaryTotalSpendingText: "#16240A",
          summarySpentBudgetText: "#FFFFFF",
          summaryTotalSavingText: "#FFFFFF",

          summaryLabelDark: "#111111",
          summaryLabelLight: "#FFFFFF",

          summaryValueDark: "#050505",
          summaryValueLight: "#FFFFFF",
        },
      },
      animation: {
        "scroll-left": "scroll-left 40s linear infinite",
        "scroll-right": "scroll-right 40s linear infinite",
      },
      keyframes: {
        "scroll-left": {
          "0%": { transform: "translateX(0)" },
          "100%": { transform: "translateX(-100%)" },
        },
        "scroll-right": {
          "0%": { transform: "translateX(-100%)" },
          "100%": { transform: "translateX(0)" },
        },
      },
    },
  },
  plugins: [],
};
